Add ticket storage and retrieval method to TicketService
fabulousnesss/java-my-project pull request #1
Opened 2024-11-03 17:15 UTC by fabulousnesss

- Implemented a static Map to store up to 10 tickets
- Added a method to retrieve a ticket by ID using Optional for safety

2024-11-06 14:46 UTC, Darya-Drutsko requested changes
Also would be great to organise the code into different packages

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/AbstractPrintable.java
> +public abstract class AbstractPrintable implements Identifiable {
Please use adjectives in naming for interfaces, for class names need to use nouns
Also try to avoid duplication of keyword in naming

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/AbstractPrintable.java
> +public abstract class AbstractPrintable implements Identifiable {
Why have you chosen here abstract class?

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/Identifiable.java
> +public interface Identifiable {
Why have you chosen here interface?

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/Client.java
> +    public Ticket getTicket() {
seems like getter -> what about adding field here?

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/AbstractPrintable.java
> +        System.out.println(this.toString());
what about overriding toString for new custom class?)

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/Admin.java
> +        return true;
not quite meaningful result) Let's check smth here :)

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/User.java
> +
Why the method is empty?)

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/Ticket.java
> +    public @interface NullableWarning {
create please new file for NullableWarning annotation

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/Ticket.java
> +    private void printNullableWarnings() {
The same here -  printNullableWarnings - not the responsibility for Ticket class

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/Ticket.java
> +        return true;
Add, please, some checks here also

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/Ticket.java
> +        return true;
Add, please, some checks here also

2024-11-06 14:46 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/Ticket.java
> +    public @interface NullableWarning {
Do you use anywhere the annotation?

2024-11-07 06:45 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/Identifiable.java
> +public interface Identifiable {
I've used an Interface to provide a contract for classes, guaranteeing that each object will have something to identify them without any constraints on their structure approach. They will decide how to manage it, thereby not binding them to the rigid hierarchy offered by abstract classes.

2024-11-07 07:42 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/AbstractPrintable.java
> +public abstract class AbstractPrintable implements Identifiable {
I've used an abstract class implementing 'Identifiable' Interface to offer shared functionality between related subclasses, providing a way to narrow diverse object types with common functionality. This approach also offers an alternative if the structural approach fits the objects, by that reducing code duplication.

2024-11-07 07:50 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/AbstractPrintable.java
> +public abstract class AbstractPrintable implements Identifiable {
Got it! Changed 'AbstractPrintable' to 'Identity' name.

2024-11-07 07:54 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/AbstractPrintable.java
> +        System.out.println(this.toString());
Got it! Added overridden 'toString' method for custom 'Identity' class.

2024-11-07 09:04 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/User.java
> +
Got it! Added the logic to print the role of the object based on its role field.

2024-11-07 09:13 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/Client.java
> +    public Ticket getTicket() {
Got it! Added 'ticket' field, getter and setter.

2024-11-07 09:34 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/Admin.java
> +        return true;
Got it! Added an eventCode check for the ticket.

2024-11-07 09:41 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/Ticket.java
> +        return true;
Got it! Added the phoneNumber and email checks.

2024-11-07 10:56 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/Ticket.java
> +    public @interface NullableWarning {
Got it! Created new file for 'NullableWarning' annotations.

2024-11-07 10:57 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/Ticket.java
> +    public @interface NullableWarning {
Added use case for the annotation.

2024-11-07 10:58 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/Ticket.java
> +    private void printNullableWarnings() {
Got it! Moved it into 'AnnotationUtils' class.

2024-11-17 16:34 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/core/Identifiable.java
> +public interface Identifiable {
 remove please this interface, this is not needed because getId and sendId should be always with the id field, so we could put methods in abstract class

2024-11-17 16:34 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/core/Identity.java
> +        System.out.println(this.toString());
this is no needed here :)

2024-11-17 16:34 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/core/User.java
> +    private String role;
looks like could be enum

2024-11-17 16:34 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/models/Ticket.java
> +        return phoneNumber != null && email != null;
not really meaningful checks, but let it be :)

2024-11-17 16:34 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/utils/AnnotationUtils.java
> +    public @interface NullableWarning {
create please separate file for @interface

2024-11-17 18:07 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/utils/AnnotationUtils.java
> +    public @interface NullableWarning {
You've already mentioned it in the second pull request, so I addressed it there. Second pull request link: https://github.com/fabulousnesss/java-my-project/pull/2

2024-11-17 18:24 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/core/Identity.java
> +        System.out.println(this.toString());
Got it! I will remove it in the second pull request: https://github.com/fabulousnesss/java-my-project/pull/2

2024-11-17 18:25 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/core/Identifiable.java
> +public interface Identifiable {
Got it! I will remove it in the second pull request: https://github.com/fabulousnesss/java-my-project/pull/2

2024-11-17 18:27 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/core/User.java
> +    private String role;
Got it! I will change it in the second pull request: https://github.com/fabulousnesss/java-my-project/pull/2

2024-11-21 08:57 UTC, merged