Refactor 'Ticket' classes and Implement 'BusTicket' parsing functionality, custom validation rules and Created custom exception class
fabulousnesss/java-my-project pull request #2
Opened 2024-11-11 14:21 UTC by fabulousnesss

This pull request introduces several key changes and improvements:
1. **Refactor 'Ticket' classes:**
    - Introduced an abstract 'Ticket' class, from which the 'BusTicket' class is derived. This refactor separates the functionalities of 'ConcertTicket' and 'BusTicket'.

2. **'BusTicket' parsing functionality:**
    - Implemented functionality to read bus tickets from a file, ensuring each field is parsed individually within its respective function.
    - The parsing logic follows the task constraints and includes detailed error handling using 'TicketValidationException' to provide meaningful error messages.

3. **Validation methods and rules:**
    - Added 'TicketValidationError' enum to group custom validation errors with specific codes and messages for 'ticketType', 'price', and 'startDate' fields of the 'Ticket' class.
    - 'TicketValidationException' class extends 'RuntimeException' and is used to handle validation errors, encapsulating specific error information.
    - Implemented 'tryParse' methods to handle field-specific parsing and validation and updating 'counters' and 'flags' according to task rules.
    - Introduced 3 additional validation methods corresponding to specific rules.
    - The 'updateCountersAndFlags' method can be used to set up new custom validation rules with the provided flag and to specify how the custom condition should be treated.

6. **Display updated information:**
    - Ensured the 'displayBusTicketsInfo' method shows the updated information after validations are applied.

2024-11-12 15:28 UTC, Darya-Drutsko requested changes

2024-11-12 15:28 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/utils/FIleUtils.java
> +    public static final String FILE_PATH = "C://tempFolder//doc.txt";
usually we try to avoid to use absolute path. What will be if I try to run on my local machine, where Mac OS installed?

2024-11-12 15:28 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/utils/AnnotationUtils.java
> +    public @interface NullableWarning {
Create please separate file for the annotation

2024-11-12 15:28 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/services/TicketService.java
> +    public static void main(String[] args) {
raise the method to the top

2024-11-12 15:28 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/services/TicketService.java
> +    public static void tryParseTicketClass(BusTicket busTicket, String ticketClassValue) {
separate please methods by different classes
Also avoid 'try' in method name

2024-11-12 15:28 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/services/TicketService.java
> +        if (ticketClassValue.equals("NULL")) {
what about null check?

2024-11-12 15:28 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/models/BusTicket.java
> +    public enum BusTicketViolationCounter {
each enum - separate file

2024-11-12 15:28 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/models/BusTicket.java
> +    private static final Map<Integer, BusTicket> busTickets = new HashMap<>();
seems like BusTicket doesn't have busTickets inside, busTickets should be in separate class

2024-11-12 15:28 UTC, Darya-Drutsko commented on src/main/java/com/fabulousnesss/myproject/exception/TicketValidationError.java
> +    private final Integer code;
Why do we need code here? What does it show?)

2024-11-14 14:18 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/utils/FIleUtils.java
> +    public static final String FILE_PATH = "C://tempFolder//doc.txt";
Got it! Now the 'readTicketsFromFile' method can read directories irrespective of the OS, but I didn't provide the '.txt' file in the project to read bus tickets from. So, you need to manually provide your own '.txt' file with data and add the path to the 'application.properties' file within the 'resources' package in the 'bus_tickets.file.path=[your absolute path]' field. If you do not want to use an absolute path, you can use a relative one. Just put your text file in the 'resources' package and provide the name of your '.txt' file here: 'String busTicketsFilePath = "[.txt file name]";' in the 'readTicketsFromFile' method and then rebuild the project to be visible at runtime in the classpath. I use the default IntelliJ build tool, so I manually marked the 'resources' package as the 'Resource root' in the 'Project structure->Modules' making all files within it accessible at runtime via the ClassLoader. I also added 'application.properties' to the 'Resource pattern' in the 'Settings->Compiler->Resource patterns' so that it is included in the build output directory and can be accessed in the classpath.

2024-11-14 14:34 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/utils/AnnotationUtils.java
> +    public @interface NullableWarning {
Got it! 'NullableWarning' interface was moved to a separate file

2024-11-14 15:09 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/services/TicketService.java
> +        if (ticketClassValue.equals("NULL")) {
Got it! Added null checks for 'parse' and custom validation methods in 'BusTicketService', also, to 'addTicketToBusTickets' method in the BusTicket class.

2024-11-14 15:44 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/models/BusTicket.java
> +    public enum BusTicketViolationCounter {
Got it! The enums in question were moved to their own respective source files.

2024-11-14 16:30 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/exception/TicketValidationError.java
> +    private final Integer code;
In cases where it isn't important to handle specific String values, Integer values could be used, since int primitive type require fewer CPU cycles it operates faster.

2024-11-21 08:29 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/resources/application.properties
> +bus_tickets.file.path=C://tempFolder//doc.txt
Got it! Changed 'C://tempFolder//doc.txt' to 'doc.txt'.

2024-11-21 08:33 UTC, fabulousnesss commented on src/main/java/com/fabulousnesss/myproject/utils/FIleUtils.java
> +    public static final String FILE_PATH = "C://tempFolder//doc.txt";
Got it! Moved 'resources' package under 'src/main/' directory and marked as the 'Resource root'. Also, avoided absolute path usage.

2024-11-21 08:55 UTC, merged